source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'RWPPageScrollView_Example' do
  pod 'RWPPageScrollView', :path => '../'

  target 'RWPPageScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
